// FILE: app/src/main/java/com/example/kisanbandhu/activities/SoilAnalysisActivity.java
package com.example.kisanbandhu.activities;

import android.content.Intent;
import android.os.Bundle;
import android.widget.Button;
import android.widget.TextView;
import android.widget.Toast;

import androidx.appcompat.app.AppCompatActivity;

import com.example.kisanbandhu.R;
import com.example.kisanbandhu.models.Soil;
import com.example.kisanbandhu.utils.PrefsManager;
import com.example.kisanbandhu.utils.SoilAnalyzer;

/**
 * SCREEN 3 - SOIL ANALYSIS.
 *
 * Reads the Soil profile that was just saved by SoilInputActivity and
 * displays it, along with a rule-based explanation generated by
 * SoilAnalyzer (see utils/SoilAnalyzer.java for the logic).
 */
public class SoilAnalysisActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_soil_analysis);

        // Defensive check: if somehow this screen is opened without a
        // saved profile (e.g. user navigated here directly, or cleared
        // app data), send them back to fill the form instead of crashing.
        if (!PrefsManager.hasSoilProfile(this)) {
            Toast.makeText(this, "Please fill in your soil information first", Toast.LENGTH_SHORT).show();
            startActivity(new Intent(this, SoilInputActivity.class));
            finish();
            return;
        }

        Soil soil = PrefsManager.getSoilProfile(this);

        TextView tvSoilType = findViewById(R.id.tvSoilType);
        TextView tvFertility = findViewById(R.id.tvFertility);
        TextView tvPH = findViewById(R.id.tvPH);
        TextView tvLocation = findViewById(R.id.tvLocation);
        TextView tvIrrigation = findViewById(R.id.tvIrrigation);
        TextView tvSeason = findViewById(R.id.tvSeason);
        TextView tvExplanation = findViewById(R.id.tvAnalysisExplanation);
        Button btnContinue = findViewById(R.id.btnContinueToCrops);

        tvSoilType.setText("Soil Type: " + soil.getSoilType());
        tvFertility.setText("Soil Fertility: " + soil.getFertility());
        tvPH.setText(soil.hasPH() ? ("Soil pH: " + soil.getSoilPH()) : "Soil pH: Not provided");
        tvLocation.setText("Location: " + soil.getDistrict() + ", " + soil.getState());
        tvIrrigation.setText("Irrigation: " + soil.getIrrigationLabel());
        tvSeason.setText("Season: " + soil.getSeason());

        // This is the key line for your viva: the explanation text comes
        // entirely from SoilAnalyzer's rule-based logic, not a live AI call.
        tvExplanation.setText(SoilAnalyzer.generateAnalysis(soil));

        // Phase 3: this now opens the real Crop Recommendation screen.
        btnContinue.setOnClickListener(v ->
                startActivity(new Intent(this, CropRecommendationActivity.class)));
    }
}
